[package]
name = "sorted_vector_map"
edition = "2018"
version = "0.1.0"
authors = ['Facebook <opensource+crates-sorted-vector-map@fb.com>']
license = "MIT OR Apache-2.0"
description = "maps and sets backed by sorted vectors"
homepage = "https://github.com/facebookexperimental/rust-shed/"
repository = "https://github.com/facebookexperimental/rust-shed"
readme = "README.md"
keywords = ["map", "set"]
categories = ["data-structures"]
include = ["README.*", "benches/**/*.rs", "src/**/*.rs"]

[[bench]]
name = "map"
harness = false

[[bench]]
name = "set"
harness = false

[dependencies]
quickcheck = "0.9"

[dev-dependencies]
itertools = "0.8"
