[package]
name = "slog_stats"
edition = "2018"
version = "0.1.0"
authors = ['Facebook <opensource+rust-shed@fb.com>']
license = "MIT OR Apache-2.0"
description = "Enables exposing counters for number of slog records per level"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../README.md"
include = ["src/**/*.rs"]

[dependencies]
stats = { path = "../stats", version = "0.1.0" }
slog = { version = "2.5", features = ["max_level_debug"] }
