[package]
name = "slog_stats"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Enables exposing counters for number of slog records per level"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
slog = { version = "2.5", features = ["max_level_trace"] }
stats = { version = "0.1.0", path = "../stats" }
