[patch.crates-io]
daemonize = { git = "https://github.com/krallin/daemonize", rev = "f7be28efa1b4a70e43bb37b5f4ff4d664992edca" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "033ebaae69beeb0ac04e8c35d6ff1103487bd9a3" }
mockall = { git = "https://github.com/fbsource/mockall", rev = "4bc4ff4ab7d04ebaa7e7c9510a3337b7dda9d324" }
mockall_derive = { git = "https://github.com/fbsource/mockall", rev = "4bc4ff4ab7d04ebaa7e7c9510a3337b7dda9d324" }
mysql_common = { git = "https://github.com/iammxt/rust_mysql_common", rev = "0e4c86952f1e799960e736c0b2bb9d2a6d935bf1" }
object = { git = "https://github.com/gimli-rs/object", rev = "9271d2cd06d1fed11259225d915178fe3824a56d" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
shellexpand = { git = "https://github.com/fanzeyi/shellexpand.git", rev = "179447a3f8fccd765acfd2eed15a54c716c49cfe" }
tokio-core = { git = "https://github.com/bolinfest/tokio-core", rev = "5f37aa3c627d56ee49154bc851d6930f5ab4398f" }
toml = { git = "https://github.com/jsgf/toml-rs", branch = "dotted-table-0.5.7" }

[workspace]
members = [
  "shed/ascii_ext",
  "shed/async_compression",
  "shed/async_once_cell",
  "shed/borrowed",
  "shed/bytes_ext",
  "shed/cached_config",
  "shed/cachelib_stub",
  "shed/chrome_trace",
  "shed/cloned",
  "shed/codegen_includer_proc_macro",
  "shed/facet",
  "shed/facet/proc_macros",
  "shed/failure_ext",
  "shed/fbinit",
  "shed/fbinit/fbinit-tokio",
  "shed/fbinit/fbinit-tokio-02",
  "shed/fbinit/macros",
  "shed/fbthrift_ext/fbthrift_ext-02/framed",
  "shed/fbthrift_ext/fbthrift_ext-02/socket",
  "shed/fbthrift_ext/fbthrift_ext-02/tcp",
  "shed/fbthrift_ext/fbthrift_ext-02/util",
  "shed/fbthrift_ext/fbthrift_ext/framed",
  "shed/fbthrift_ext/fbthrift_ext/socket",
  "shed/fbthrift_ext/fbthrift_ext/tcp",
  "shed/fbthrift_ext/fbthrift_ext/util",
  "shed/futures_01_ext",
  "shed/futures_ext",
  "shed/futures_stats",
  "shed/hash_memo",
  "shed/hostcaps",
  "shed/hostname",
  "shed/limited_async_read",
  "shed/lock_ext",
  "shed/memcache_stub",
  "shed/memcache_stub/common",
  "shed/netstring",
  "shed/panichandler",
  "shed/perthread",
  "shed/scuba_sample",
  "shed/scuba_stub",
  "shed/secure_utils",
  "shed/serde_starlark",
  "shed/services",
  "shed/services/common",
  "shed/shared_error",
  "shed/slog_glog_fmt",
  "shed/slog_stats",
  "shed/sorted_vector_map",
  "shed/sql",
  "shed/sql/common",
  "shed/sql/derive",
  "shed/sql/tests_lib",
  "shed/stats",
  "shed/stats/traits",
  "shed/thrift_compiler",
  "shed/time_ext",
  "shed/tokio-uds-compat/tokio-uds-compat",
  "shed/tokio-uds-compat/tokio-uds-compat-02",
  "shed/tokio_shim",
]
