[patch.crates-io]
daemonize = { git = "https://github.com/krallin/daemonize", rev = "f7be28efa1b4a70e43bb37b5f4ff4d664992edca" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "033ebaae69beeb0ac04e8c35d6ff1103487bd9a3" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
quickcheck = { git = "https://github.com/jakoschiko/quickcheck", rev = "6ecdf5bb4b0132ce66670b4d46453aa022ea892c" }
reqwest = { git = "https://github.com/vmagro/reqwest", rev = "b08239c2b6c837321a697c5bb2be394d276b59ca" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
shellexpand = { git = "https://github.com/fanzeyi/shellexpand.git", rev = "179447a3f8fccd765acfd2eed15a54c716c49cfe" }
toml = { git = "https://github.com/fbsource/toml", branch = "dotted-table-0.5.8" }

[workspace]
members = [
  "shed/ascii_ext",
  "shed/async_compression",
  "shed/async_once_cell",
  "shed/borrowed",
  "shed/bytes_ext",
  "shed/cached_config",
  "shed/cachelib_stub",
  "shed/chrome_trace",
  "shed/cloned",
  "shed/codegen_includer_proc_macro",
  "shed/facet",
  "shed/facet/proc_macros",
  "shed/failure_ext",
  "shed/fbinit",
  "shed/fbinit/fbinit-tokio",
  "shed/fbinit/fbinit-tokio-02",
  "shed/fbinit/macros",
  "shed/fbthrift_ext/framed",
  "shed/fbthrift_ext/socket",
  "shed/fbthrift_ext/tcp",
  "shed/fbthrift_ext/util",
  "shed/futures_01_ext",
  "shed/futures_ext",
  "shed/futures_stats",
  "shed/hash_memo",
  "shed/hostcaps",
  "shed/hostname",
  "shed/limited_async_read",
  "shed/lock_ext",
  "shed/memcache_stub",
  "shed/memcache_stub/common",
  "shed/netstring",
  "shed/panichandler",
  "shed/perthread",
  "shed/scuba_sample",
  "shed/scuba_stub",
  "shed/secure_utils",
  "shed/serde_starlark",
  "shed/services",
  "shed/services/common",
  "shed/shared_error",
  "shed/slog_glog_fmt",
  "shed/slog_stats",
  "shed/sorted_vector_map",
  "shed/sql",
  "shed/sql/common",
  "shed/sql/derive",
  "shed/sql/tests_lib",
  "shed/stats",
  "shed/stats/traits",
  "shed/thrift_compiler",
  "shed/time_ext",
  "shed/tokio-uds-compat/tokio-uds-compat",
  "shed/tokio_shim",
]
