[patch.crates-io]
abomonation = { git = "https://github.com/markbt/abomonation", rev = "0f43346d2afa2aedc64d61f3f4273e8d1e454642" }
base64urlsafedata = { git = "https://github.com/kanidm/webauthn-rs.git", rev = "b6d1dc410b7b2387157f2e089391cff7104aa05b" }
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", rev = "2997017b5a3065b83e9d76f0080d6cb99c94c0c1" }
bindgen-cli = { git = "https://github.com/rust-lang/rust-bindgen", rev = "2997017b5a3065b83e9d76f0080d6cb99c94c0c1" }
graphql-parser = { git = "https://github.com/graphql-rust//graphql-parser", rev = "8d76425d83c40670570cc325f57c730262f07456" }
imgui = { git = "https://github.com/imgui-rs/imgui-rs.git", rev = "47bb38be50fafe99021b6436672dea1c28920e70" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "fdbf843d174c6796d736b2b61dab0297670390f8" }
perf-event = { version = "0.4", git = "https://github.com/krallin/perf-event.git", rev = "86224a9bc025d5d19f719542f27c8c629a08b167" }
perf-event-open-sys = { version = "4.0", git = "https://github.com/krallin/perf-event.git", rev = "86224a9bc025d5d19f719542f27c8c629a08b167" }
quickcheck = { git = "https://github.com/jakoschiko/quickcheck", rev = "6ecdf5bb4b0132ce66670b4d46453aa022ea892c" }

[workspace]
members = [
  "shed/ascii_ext",
  "shed/async_compression",
  "shed/async_once_cell",
  "shed/borrowed",
  "shed/bytes_ext",
  "shed/cached_config",
  "shed/cachelib_stub",
  "shed/chrome_trace",
  "shed/cloned",
  "shed/codegen_includer_proc_macro",
  "shed/detect_eden",
  "shed/facet",
  "shed/facet/proc_macros",
  "shed/failure_ext",
  "shed/fbinit",
  "shed/fbinit/fbinit-tokio",
  "shed/fbinit/fbinit_macros",
  "shed/fbthrift_ext/adapters",
  "shed/fbthrift_ext/framed",
  "shed/fbthrift_ext/socket",
  "shed/fbthrift_ext/tcp",
  "shed/fbthrift_ext/util",
  "shed/futures_01_ext",
  "shed/futures_ext",
  "shed/futures_lazy_shared",
  "shed/futures_stats",
  "shed/hash_memo",
  "shed/hlist_to_tuple",
  "shed/hostcaps",
  "shed/hostname",
  "shed/justknobs_stub",
  "shed/justknobs_stub/cached_config_thrift_struct",
  "shed/justknobs_stub/cached_config_thrift_struct/types",
  "shed/limited_async_read",
  "shed/lock_ext",
  "shed/memcache_stub",
  "shed/memcache_stub/common",
  "shed/netstring",
  "shed/ods",
  "shed/panichandler",
  "shed/perthread",
  "shed/quickcheck_arbitrary_derive",
  "shed/scuba_sample",
  "shed/scuba_sample/derive",
  "shed/scuba_sample/derive_tests",
  "shed/scuba_stub",
  "shed/secure_utils",
  "shed/services",
  "shed/services/common",
  "shed/shared_error",
  "shed/slog_glog_fmt",
  "shed/slog_stats",
  "shed/sorted_vector_map",
  "shed/sql",
  "shed/sql/common",
  "shed/sql/derive",
  "shed/sql/tests_lib",
  "shed/stats",
  "shed/stats/traits",
  "shed/thrift_compiler",
  "shed/time_ext",
  "shed/tokio-uds-compat",
]
resolver = "2"
