[package]
name = "fbthrift_tcp-02"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "fbthrift extensions for tcp transport"
readme = "../../../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[lib]
name = "fbthrift_tcp"
path = "lib.rs"

[dependencies]
anyhow = "1.0"
bytes = { version = "1.0", features = ["serde"] }
const-cstr = "0.3.0"
fbthrift = { version = "0.0.1+unstable", git = "https://github.com/facebook/fbthrift.git", branch = "master" }
fbthrift_framed-02 = { version = "0.1.0", path = "../framed" }
fbthrift_util-02 = { version = "0.1.0", path = "../util" }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
tokio = { version = "0.2.25", features = ["full", "test-util"] }
tokio-tower = "0.4"
tokio-util = { version = "0.3", features = ["codec", "udp"] }
tower-service = "0.3"
