[package]
name = "thrift_compiler"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/lib.rs", "src/main.rs", "tests/*.rs"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "compiler"
path = "src/main.rs"

[[test]]
name = "tests"
path = "tests/main.rs"

[dependencies]
anyhow = "1.0"
clap = "2.33"

[dev-dependencies]
lazy_static = "1.4"
regex = "1.3"
tempdir = "0.3"
