[package]
name = "fbthrift_tcp"
edition = "2018"
version = "0.1.0"
authors = ['Facebook <opensource+rust-shed@fb.com>']
license = "MIT OR Apache-2.0"
description = "fbthrift extensions for tcp transport"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../../README.md"

[lib]
path = "lib.rs"

[dependencies]
fbthrift_framed = { path = "../framed", version = "0.1.0" }
fbthrift_util = { path = "../util", version = "0.1.0" }
fbthrift = { git = "https://github.com/facebook/fbthrift.git", branch = "master", version = "0.0.1+unstable" }
anyhow = "1.0"
bytes = { version = "0.5", features = ["serde"] }
bytes-old = { package = "bytes", version = "0.4", features = ["serde"] }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
tokio = { version = "0.2.25", features = ["full", "test-util"] }
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
tokio-tower = "0.4"
tokio-util = { version = "0.2", features = ["codec", "udp"] }
tower-service = "0.3"
