[package]
name = "netstring"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
anyhow = "1.0"
bytes = { version = "0.4", features = ["serde"] } # todo: remove
thiserror = "1.0"
tokio-io = "0.1"

[dev-dependencies]
quickcheck = "0.9"
