name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.55.0
        default: true
        profile: minimal
    - name: Install system deps
      run: sudo python3 build/fbcode_builder/getdeps.py --allow-system-packages install-system-deps --recursive mononoke
    - name: Build dependencies
      run: python3 build/fbcode_builder/getdeps.py build --allow-system-packages --only-deps --src-dir=. rust-shed
    - name: Build rust-shed
      run: python3 build/fbcode_builder/getdeps.py build --allow-system-packages --no-deps --src-dir=. rust-shed
    - name: Copy artifacts
      run: python3 build/fbcode_builder/getdeps.py fixup-dyn-deps --allow-system-packages --src-dir=. rust-shed _artifacts/linux
    - uses: actions/upload-artifact@master
      with:
        name: rust-shed
        path: _artifacts
    - name: Test rust-shed
      run: python3 build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
    - name: Install Rust Beta
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        default: true
        profile: minimal
    - name: Test rust-shed with beta toolchain
      run: python3 build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
      continue-on-error: true
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        profile: minimal
    - name: Test rust-shed with nightly toolchain
      run: python3 build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
      continue-on-error: true
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.55.0
        default: true
        profile: minimal
    - name: Install system deps
      run: sudo python3 build/fbcode_builder/getdeps.py --allow-system-packages install-system-deps --recursive mononoke
    - name: Build dependencies
      run: python3 build/fbcode_builder/getdeps.py build --allow-system-packages --only-deps --src-dir=. rust-shed
    - name: Build rust-shed
      run: python3 build/fbcode_builder/getdeps.py build --allow-system-packages --no-deps --src-dir=. rust-shed
    - name: Copy artifacts
      run: python3 build/fbcode_builder/getdeps.py fixup-dyn-deps --allow-system-packages --src-dir=. rust-shed _artifacts/mac
    - uses: actions/upload-artifact@master
      with:
        name: rust-shed
        path: _artifacts
    - name: Test rust-shed
      run: python3 build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
    - name: Install Rust Beta
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        default: true
        profile: minimal
    - name: Test rust-shed with beta toolchain
      run: python3 build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
      continue-on-error: true
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        profile: minimal
    - name: Test rust-shed with nightly toolchain
      run: python3 build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
      continue-on-error: true
  windows:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.55.0
        default: true
        profile: minimal
    - name: Export boost environment
      run: "echo name=BOOST_ROOT::%BOOST_ROOT_1_69_0% >> $GITHUB_ENV"
    - name: Fix Git config
      run: git config --system core.longpaths true
    - name: Build dependencies
      run: python build/fbcode_builder/getdeps.py build --allow-system-packages --only-deps --src-dir=. rust-shed
    - name: Build rust-shed
      run: python build/fbcode_builder/getdeps.py build --allow-system-packages --no-deps --src-dir=. rust-shed
    - name: Copy artifacts
      run: python build/fbcode_builder/getdeps.py fixup-dyn-deps --allow-system-packages --src-dir=. rust-shed _artifacts/windows
    - uses: actions/upload-artifact@master
      with:
        name: rust-shed
        path: _artifacts
    - name: Test rust-shed
      run: python build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
    - name: Install Rust Beta
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        default: true
        profile: minimal
    - name: Test rust-shed with beta toolchain
      run: python build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
      continue-on-error: true
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        profile: minimal
    - name: Test rust-shed with nightly toolchain
      run: python build/fbcode_builder/getdeps.py test --allow-system-packages --src-dir=. rust-shed
      continue-on-error: true
